source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false


gem 'active_model_serializers'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  #below are all added in
  gem 'pry-rails'

  #S: creates instances of models for testing instead of creating and saving instances. Also helps if you need to create 100s of instances
  gem 'factory_bot_rails'

  #S: generates random data
  gem 'faker'

  gem 'rspec-rails' #fixed spec not seeing class

  gem 'rails-controller-testing' #assert template is its own gem. told to put here

end

group :development do
  #added the below:
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'


  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # S: Gives us ability to write rspec code in rails app
  #S: we also have to run 'rails g rspec:install' in the terminal after bundle install
  #S: if you go to generated .rspec file, you can add:
  # --color
  # --format documentation
  # these two flags make things easier to read
  gem 'rspec-rails'


  #S: gives us ability to test our models and associations with nice one liners. Also gives more detailed error messages
  gem 'shoulda-matchers'
  #S: we can launch external applications from within rails app. 
  #S: if we are testing a featuer and want to see what our form looks like, 
  #S: we can lauche the web browser to show us what our test looks like in our application
  gem 'launchy'

  # Adds support for Capybara system testing and selenium driver
  #S: capybara simulates who a user interacts with app. Tests our views
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
  gem 'webdriver'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
